name: Sync WebDAV Files and Publish

on:
  workflow_dispatch:  # Lancer manuellement

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install webdavclient3 python-dotenv

      - name: Run sync script
        env:
          WEBDAV_HOSTNAME: ${{ secrets.WEBDAV_HOSTNAME }}
          WEBDAV_LOGIN: ${{ secrets.WEBDAV_LOGIN }}
          WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}
          DOWNLOAD_DIR: cdn
        run: python sync.py

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cdn
