name: Sync WebDAV Files

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      WEBDAV_HOSTNAME: ${{ secrets.WEBDAV_HOSTNAME }}
      WEBDAV_LOGIN: ${{ secrets.WEBDAV_LOGIN }}
      WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}
      DOWNLOAD_DIR: active

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install webdavclient3 python-dotenv

      - name: Run sync script
        run: python sync.py
